apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.projectName }}
  labels:
    apps: "{{ .Values.workerLocation }}-named"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.named.replicaCount }}
  selector:
    matchLabels:
      {{- include "bind9-centos7.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if eq .Values.workerLocation "test" }}
        k8s.v1.cni.cncf.io/networks: {{- toYaml .Values.named.multusIPs.test | indent 1 }}
      {{- else if eq .Values.workerLocation "pangyo" }}
        k8s.v1.cni.cncf.io/networks: {{- toYaml .Values.named.multusIPs.pangyo | indent 1 }}
      {{- end }}
      labels:
        {{- include "bind9-centos7.selectorLabels" . | nindent 8 }}
    spec:
      nodeSelector:
        location-node: "{{ .Values.workerLocation }}"
      {{- with .Values.named.dnsSettings }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.named.securityContext | nindent 12 }}
          image: {{ template "bind9-centos7.named.image" . }}
          imagePullPolicy: {{ .Values.named.image.pullPolicy }}
          resources:
            {{- toYaml .Values.named.resources | nindent 12 }}
          volumeMounts:
          {{- toYaml .Values.named.volumeMounts | nindent 10 }}
      volumes:
      - name: v1
        configMap:
          name: {{ .Release.Name }}-config-configmap
      - name: v2
        configMap:
          name: {{ .Release.Name }}-zones-configmap
